package manager
/*
Copyright 2026 Erling Kristiansen.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at


























































































































}	return defaultValue	}		return value == "true" || value == "1" || value == "yes"	if value, exists := os.LookupEnv(key); exists {func getEnvBool(key string, defaultValue bool) bool {}	return defaultValue	}		return value	if value, exists := os.LookupEnv(key); exists {func getEnv(key, defaultValue string) string {}	}		os.Exit(1)		setupLog.Error(err, "problem running manager")	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {	setupLog.Info("starting manager")	}		os.Exit(1)		setupLog.Error(err, "unable to set up ready check")	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {	}		os.Exit(1)		setupLog.Error(err, "unable to set up health check")	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {	}		os.Exit(1)		setupLog.Error(err, "unable to create controller", "controller", "OpenClaw")	}).SetupWithManager(mgr); err != nil {		Config: config,		Scheme: mgr.GetScheme(),		Client: mgr.GetClient(),	if err = (&controller.OpenClawReconciler{	}		GitInitImage:                getEnv("GIT_INIT_IMAGE", "alpine/git:latest"),		OpenClawImage:               getEnv("OPENCLAW_IMAGE", "ghcr.io/openclaw/openclaw:latest"),		DefaultEgressMode:           getEnv("DEFAULT_SECURITY_EGRESS_MODE", "whitelist"),		DefaultSandboxNetworkPolicy: getEnvBool("DEFAULT_SECURITY_SANDBOX_NETWORK_POLICY", true),		DefaultSandboxSeccomp:       getEnvBool("DEFAULT_SECURITY_SANDBOX_SECCOMP", true),		DefaultSandboxLandlock:      getEnvBool("DEFAULT_SECURITY_SANDBOX_LANDLOCK", true),		DefaultSandboxEnabled:       getEnvBool("DEFAULT_SECURITY_SANDBOX_ENABLED", true),	config := controller.Config{	// Get configuration from environment	}		os.Exit(1)		setupLog.Error(err, "unable to create manager")	if err != nil {	})		LeaderElectionID:       "kubeclaw-operator.openclaw.io",		LeaderElection:         enableLeaderElection,		HealthProbeBindAddress: probeAddr,		},			BindAddress: metricsAddr,		Metrics: metricsserver.Options{		Scheme: scheme,	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))	flag.Parse()	opts.BindFlags(flag.CommandLine)	}		Development: logLevel == "debug",	opts := zap.Options{	flag.StringVar(&logLevel, "log-level", "info", "Log level (debug, info, warn, error)")			"Enabling this will ensure there is only one active controller manager.")		"Enable leader election for controller manager. "+	flag.BoolVar(&enableLeaderElection, "leader-elect", false,	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")	flag.StringVar(&metricsAddr, "metrics-bind-address", ":8080", "The address the metric endpoint binds to.")	var logLevel string	var enableLeaderElection bool	var probeAddr string	var metricsAddr stringfunc main() {}	utilruntime.Must(openclawv1alpha1.AddToScheme(scheme))	utilruntime.Must(clientgoscheme.AddToScheme(scheme))func init() {)	setupLog = ctrl.Log.WithName("setup")	scheme   = runtime.NewScheme()var ()	"github.com/egkristi/kubeclaw/internal/controller"	openclawv1alpha1 "github.com/egkristi/kubeclaw/api/v1alpha1"	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"	"sigs.k8s.io/controller-runtime/pkg/log/zap"	"sigs.k8s.io/controller-runtime/pkg/healthz"	ctrl "sigs.k8s.io/controller-runtime"	clientgoscheme "k8s.io/client-go/kubernetes/scheme"	utilruntime "k8s.io/apimachinery/pkg/util/runtime"	"k8s.io/apimachinery/pkg/runtime"	"os"	"flag"import (package main*/limitations under the License.See the License for the specific language governing permissions andWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.distributed under the License is distributed on an "AS IS" BASIS,Unless required by applicable law or agreed to in writing, software    http://www.apache.org/licenses/LICENSE-2.0